[project]
name = "kitty3000-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ceven Jupiter Knowles", email = "160178756+CevenJKnowles@users.noreply.github.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "pandas>=3.0.5",
    "panns-inference>=0.1.1",
    "torch>=2.14.0",
    "torchaudio>=2.11.0",
    "torchcodec>=0.16.0",
    "fastapi>=0.141.1",
    "librosa>=1.0.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "python-multipart>=0.0.32",
    "uvicorn[standard]>=0.52.4",
    "scikit-learn>=1.9.0",
    "tqdm>=4.70.0",
    "joblib>=1.6.0",
]

[project.scripts]
kitty3000-ml = "kitty3000_ml:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipykernel>=7.3.0",
    "ipython>=9.17.1",
]
